@startuml DecodingAlgorithm

start
:Get intensity/brightness
values for each quadrant
from the current frame;
:Compute the sample variance
of the brightness values;
:Compute the standard deviation
of the brightness values
using the sample variance;
if (standard deviation / max brightness < movement threshold) then (yes)
    :All quadrants "bright";
else (no)
    :Compute brightness threshold:
    brightness threshold = max - sensitivity*std dev;
    repeat :For each quadrant ...
        if (quadrant brightness > brightness threshold) then (yes)
            :Quadrant is "bright";
        else (no)
            :Quadrant is "dark";
        endif
    repeat while (all quadrants processed?) is (no)
    ->yes;
endif
switch (quadrant brightness permutation)
    case (0000)
        :NO_MOVE;
    case (0001)
        :PAN_RIGHT
        TILT_DOWN;
    case (0010)
        :PAN_LEFT
        TILT_DOWN;
    case (0011)
        :TILT_DOWN;
    case (0100)
        :PAN_LEFT
        TILT_UP;
    case (0101)
        :NO_MOVE;
    case (0110)
        :PAN_LEFT;
    case (0111)
        :PAN_LEFT
        TILT_DOWN;
    case (1000)
        :PAN_RIGHT
        TILT_UP;
    case (1001)
        :PAN_RIGHT;
    case (1010)
        :NO_MOVE;
    case (1011)
        :PAN_RIGHT
        TILT_DOWN;
    case (1100)
        :TILT_UP;
    case (1101)
        :PAN_RIGHT
        TILT_UP;
    case (1110)
        :PAN_LEFT
        TILT_UP;
    case (1111)
        :NO_MOVE;
    endswitch
:Push movement commands to
motor queue;
end

@enduml